### ISSUE TITLE
Does this plug-in support android?

### ISSUE THREAD

**Issue by yukitaka13-1110** [imamurh/flutter_skyway#1]
Hi @imamurh .
I read your [Qiita](https://qiita.com/imamurh/items/43966e33e100956e0998).

In your article case, android was not supported.

Do you have any plans to support android?

Thank you !

**Comment by imamurh** [comment]
Hi, @yukitaka13-1110.

Sorry, I have no plan to support Android.
And I might not update this repository any further...

This repository is an example of Flutter platform channels.
Be careful, even iOS Plug-in does not work perfectly.

Thank you.

**Comment by yukitaka13-1110** [comment]
@imamurh 
回答ありがとうございます！
別の方法を模索してみます
ありがとうございました！
